# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_employe', models.IntegerField()),
                ('id_commercant', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('confirmed', models.BooleanField(default=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
